# Generated by Django 4.1.1 on 2022-10-03 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='description',
        ),
        migrations.AlterField(
            model_name='invoicedetails',
            name='Payments',
            field=models.CharField(choices=[('Mpamba', 'Mpamba'), ('Credit_Card', 'Credit_Card'), ('Airtel_Money', 'Airtel_Money')], max_length=100),
        ),
    ]
