# Generated by Django 4.1.1 on 2022-10-03 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0003_product_uniqueid_alter_invoicedetails_payments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='ordernumber',
        ),
        migrations.AlterField(
            model_name='product',
            name='Currency',
            field=models.CharField(choices=[('k', 'kwacha'), ('$', 'USD')], default='K', max_length=100),
        ),
    ]
