# Generated by Django 4.1.1 on 2022-10-03 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0004_remove_product_ordernumber_alter_product_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoicedetails',
            name='Payments',
            field=models.CharField(choices=[('Airtel_Money', 'Airtel_Money'), ('Credit_Card', 'Credit_Card'), ('Mpamba', 'Mpamba')], max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='Currency',
            field=models.CharField(choices=[('$', 'USD'), ('k', 'kwacha')], default='K', max_length=100),
        ),
    ]
